export const INIT_ENTOURAGE = 'INIT_ENTOURAGE'
export const ERROR_INIT = 'ERROR_INIT'

export const FETCH_FEEDS = 'FETCH_FEEDS'
export const FETCH_FEEDS_SUCCEEDED = 'FETCH_FEEDS_SUCCEEDED'
export const FETCH_FEEDS_ERROR = 'FETCH_FEEDS_ERROR'
export const FILTER_FEEDS = 'FILTER_FEEDS'
export const RESET_FILTER = 'RESET_FILTER'

export const MAP_LOADED = 'MAP_LOADED'